### ISSUE TITLE
no licence :(

### ISSUE THREAD

**Issue by zmandel** [jaukia/zoomooz#102]
Hi, thanks for the great library!
I see you have not published a licence. Apparently this means that people cant put your code in a product: https://help.github.com/articles/open-source-licensing/
Can you please add one like an MIT licence?

**Comment by jauomni** [comment]
The license files are in the src directory, I could move them one level up as well.

See here, double license (GPL + MIT), choose the one you prefer:
https://github.com/jaukia/zoomooz/tree/master/src

**Comment by jaukia** [comment]
The license files are in the src directory, I could move them one level up as well.

See here, double license (GPL + MIT), choose the one you prefer:
https://github.com/jaukia/zoomooz/tree/master/src

**Comment by zmandel** [comment]
thanks for the clarification!

**Comment by MicFin** [comment]
It appears that this issue can be closed

**Comment by ianhobbs** [comment]
good idea close this
