### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by ppodgorsek** [jaukia/zoomooz#124]
From a legal perspective, the project is not usable on a commercial project without a license.

**Comment by jaukia** [comment]
Dual license, MIT + GPL, see here: https://github.com/jaukia/zoomooz/blob/master/zoomooz.jquery.json

And:
https://github.com/jaukia/zoomooz/tree/master/src

**Comment by ppodgorsek** [comment]
There is no specific mention indicating if the project can be used for commercial projects or not.
See:
* https://softwareengineering.stackexchange.com/questions/139663/confusion-about-dual-license-mit-gpl-javascript-for-use-on-my-website
* https://en.wikipedia.org/wiki/GNU_General_Public_License

**Comment by jaukia** [comment]
No there is not. If your usage doesn't fall under GPL or MIT, then it isn't covered by the licenses, sorry about that. But that is the typical case for OS-projects, I think.

But do note that the GPL license is v2, not v3:
https://github.com/jaukia/zoomooz/blob/master/src/GPL-LICENSE.txt

**Comment by dgerding** [comment]
Hi,
Just wondering which license of the “dual” covers which use?  I assume GPL for commercial and MIT for everything else?  I don’t see that anywhere so I’m confused, too 😊
Thanks

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by ppodgorsek** [comment]
Well, it's not up to the end-user to decide which license to use.
The GPLv2 contains the following statement:

> You must cause any work that you distribute or publish, that in
> whole or in part contains or is derived from the Program or any
> part thereof, to be licensed as a whole at no charge to all third
> parties under the terms of this License.

This means that you are allowed to require the code of many commercial projects using your project, limited only to derived work depending on how the implementation is done, arguing that it is covered by GPLv2 instead of MIT. (the most restrictive license usually applies)
In the case of MIT, commercial projects could use it without any problem.

**Comment by ppodgorsek** [comment]
An interesting read: https://opensource.guide/legal/

**Comment by jaukia** [comment]
This project shared originally same licensing model as jQuery to enable people to easily use this (since this requires jQuery anyways).
