### ISSUE TITLE
Zoom on a picture in a while loop is drunk

### ISSUE THREAD

**Issue by Flashtheorie** [jaukia/zoomooz#133]
So I display a list of images with a while, it works well on most of the first images but then near the end, it goes somewhere totally different when I click on an image.

le zoomTarget class is displayed like this : 

`<img  class="img-thumbnail zoomTarget';

if ($blur > 30) { echo "blur";} echo '" src="'.$photos->source.'" alt="" />`

I know from other comments that it's when you reach 50% of the scroll.

**Comment by Flashtheorie** [comment]
Well, it's been a while.

**Comment by Flashtheorie** [comment]
Well, it has been EVER MORE a while.
Does nobody check the issues or what ?

**Comment by jaukia** [comment]
Not really, no :/. This is an open-source project I made originally in 2010, that is 12 years ago. The last change was 6 years ago. So I wouldn't even know myself where the issues are without digging deeply in the code. I hope you find a solution to your problem!

**Comment by Flashtheorie** [comment]
Oh, well, I'm sorry for that then
I just close the issue, have a good one
