### ISSUE TITLE
Zoom enabling with button

### ISSUE THREAD

**Issue by rdimaunahan** [jaukia/zoomooz#134]
I am trying to implement your library into my web page and I'm a trying to do it by having buttons that will enable zoom. Currently it is not working even when I am successfully adding the class name zoomTarget into the classlist of the element I want to zoom. Below is the code I'm working on.

<button onclick="zoom()">Enable Zoom</button><button onclick="nozoom()">Disable Zoom</button></br>
var item = document.getElementsByClassName("item");
function zoom(){
	for(let i = 0; i<item.length; i++){
	console.log("zoom added");
	item[i].classList.add("zoomTarget");
	}
}
function nozoom(){
	for(let i = 0; i<item.length; i++){
	console.log("no zoom");
	item[i].classList.remove("zoomTarget");
	}
}

**Comment by jaukia** [comment]
Sorry, I haven't updated or even tested the library in almost a decade so cannot help you on this.
