### ISSUE TITLE
animationendcallback issue

### ISSUE THREAD

**Issue by ghost** [jaukia/zoomooz#65]
I've come to realize that the animationendcallback parameter isn't in fact a true callback. The name suggests that it should execute the specified callback AFTER the animation is complete, however I've tested it by placing an alert in my callback function, and the alert pops up before the animatinon even starts! This is the reason I'm getting so much laggy performance with the plugin, is because my callback function is running at the same time as the animation. Any suggestion on how to get this to perform as expected? Thanks.

**Comment by seancloney** [comment]
is it possible to have a click function on an element target a div to zoom in?  I have tried $('#div_name').zoomTo({targetsize:.4, duration:1500}); ...but the whole body zooms in.  I just want the zoomContainer to do the zooming.
