### ISSUE TITLE
zoomTo with dom elements added AFTER doc loaded/ready?

### ISSUE THREAD

**Issue by dgerding** [jaukia/zoomooz#76]
I’ve been  struggling to get zoomTo working (using an element ID).  It works in one section of my code but not in another.  I thought that everything was the same, then realized that (duh) in the case where it isn’t working that html is loaded dynamically after page load.  By not working I mean:(no exceptions, no errors, no effect)

Assuming zoomooz is doing some crawling of the html behind the scenes before load, is there some function I can call to “refresh” zoomooz to the current state of the dom?  Am I on the right track here?

To be clear: I have _lots_ of spans loaded into the dom after document.ready... and I want a to zoom in when they are double clicked or zoom back out to the whole doc, programmatically.  

Thanks!

**Comment by abulka** [comment]
see #73
