### ISSUE TITLE
Zoom Inside Container ... Programmatically?

### ISSUE THREAD

**Issue by dgerding** [jaukia/zoomooz#79]
Hi,
Is there a way to specify through settings that I want to zoom within the (or "a specified" parent) container?  I can't use html/css like in the example because we don't have content till runtime. 

Thanks in advance for any help.
Dave G

**Comment by halbano** [comment]
I am looking also to be helped with this. 

I need to zoom a div inside a container and have buttons to fire the actions. The zoom and the zoomOut. 

Would be good if someone can help us. Any thougth @jaukia?

**Comment by jaukia** [comment]
I don't remember, unfortunately, and haven't got time right now to look into this :/. If someone else can help then that would definitely be excellent!

**Comment by milos12345** [comment]
Does it work anywhere on your site? Probably issue with relative/absolute containers. My whole site uses zoomooz on several different places and I had no issues with it, examples are excellent. Try clicking first car in [http://milosparipovic.com/#/id](http://milosparipovic.com/#/id) and then thumbnail within; (-) button to zoom out. Feel free to dissect site's js.

At the bottom of 
http://milosparipovic.com/js/gallery.js
look for SubpageZoomOut() and  SubpageZoomThumb()
but I am not doing anything fancy that is not explained in zoomooz examples. First try fixing what is relative/absolute

**Comment by halbano** [comment]
Hey, thank you both for your respective answer. 

@milos12345 Many thanks for you answer and also the permit to dissect the js. I have now reduced everything to: 

```
<div class="zoomViewport">
    <div class="zoomContainer">
        <div class="zoomTarget">Target 1</div>
        <div class="zoomTarget">Target 2</div>
    </div>
</div>
```
In my html file but I cannot get the library working yet. 
No relative/absolute containers, just the mentioned hierarchy, is anything other possible reason for this behavior that shows up on your head?

**Comment by milos12345** [comment]
The problem is that you did not set up what is realative and what absolute. My container is absolute, each target is relative,

**Comment by halbano** [comment]
How the positions attributes should be to have the hierarchy working? 
As I understand from your comments @milos12345 you said something like that: 
```
<div class="zoomViewport" style:"position: absolute;">
    <div class="zoomContainer"  style:"position: absolute;"? >
        <div class="zoomTarget"  style:"position: relative;">Target 1</div>
        <div class="zoomTarget"  style:"position: relative;">Target 2</div>
    </div>
</div>
```
I cannot get this working yet.
